apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"   # <â€“ allow up to 50MB uploads
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: www.classify26.live
      http:
        paths:
          - path: /api/materials/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: materials-srv
                port:
                  number: 3000
          - path: /api/courses/[^/]+/materials(/.*)?
            pathType: ImplementationSpecific
            backend:
              service:
                name: materials-srv
                port:
                  number: 3000
          - path: /api/lessons/[^/]+/attendance(/.*)?
            pathType: ImplementationSpecific
            backend:
              service:
                name: attendance-srv
                port:
                  number: 3000
          - path: /api/courses/[^/]+/students/[^/]+/attendance(/.*)?
            pathType: ImplementationSpecific
            backend:
              service:
                name: attendance-srv
                port:
                  number: 3000
          - path: /api/attendance/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: attendance-srv
                port:
                  number: 3000
          - path: /api/users/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: users-srv
                port:
                  number: 3000
          - path: /api/reset-password/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: reset-password-srv
                port:
                  number: 3000
          - path: /api/shifts/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: shifts-srv
                port:
                  number: 3000
          - path: /api/subjects/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: subjects-srv
                port:
                  number: 3000
          - path: /api/courses/?(.*)
            pathType: ImplementationSpecific
            backend:
              service: 
                name: courses-srv
                port:
                  number: 3000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
    service.beta.kubernetes.io/do-loadbalancer-hostname: 'www.classify26.live'
  labels:
    helm.sh/chart: ingress-nginx-2.0.3
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.32.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller