apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: materials-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: materials-mysql-depl
spec:
  selector:
    matchLabels:
      app: materials-mysql
  template:
    metadata:
      labels:
        app: materials-mysql
    spec:
      volumes:
        - name: materials-mysql-storage
          persistentVolumeClaim:
            claimName: materials-mysql-pvc

      containers:
      - name: materials-mysql
        image: mysql
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            value: classify
        ports:
          - containerPort: 3306
        volumeMounts:
            - name: materials-mysql-storage
              mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: materials-mysql-srv
spec:
  selector:
    app: materials-mysql
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
