apiVersion: apps/v1
kind: Deployment
metadata:
  name: reset-password-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reset-password
  template:
    metadata:
      labels:
        app: reset-password
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z reset-password-mysql-srv 3306; do
                echo "Waiting for MySQL at reset-password-mysql-srv:3306...";
                sleep 5;
              done;
      containers:
        - name: reset-password
          image: 20011005/reset-password
          env:
            - name: MYSQL_HOST
              value: reset-password-mysql-srv
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: classify
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RabbitMQ_URL
              value: "amqp://admin:password@rabbitmq-srv:5672"
            - name: GMAIL_USER
              value: "classify266@gmail.com"
            - name: GMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: gmail-secret
                  key: GMAIL_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: reset-password-srv
spec:
  selector:
    app: reset-password
  type: ClusterIP
  ports:
    - name: reset-password-port
      protocol: TCP
      port: 3000
      targetPort: 3000