apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reset-password-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reset-password-mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reset-password-mysql
  template:
    metadata:
      labels:
        app: reset-password-mysql
    spec:
      volumes:
        - name: reset-password-mysql-storage
          persistentVolumeClaim:
            claimName: reset-password-mysql-pvc

      containers:
        - name: reset-password-mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: classify
          ports:
            - containerPort: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20  # Adjust based on MySQL startup time
            periodSeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: reset-password-mysql-storage
              mountPath: /var/lib/mysql
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: reset-password-mysql
# spec:
#   serviceName: reset-password-mysql-srv
#   replicas: 1
#   selector:
#     matchLabels:
#       app: reset-password-mysql
#   template:
#     metadata:
#       labels:
#         app: reset-password-mysql
#     spec:
#       containers:
#         - name: reset-password-mysql
#           image: mysql
#           env:
#             - name: MYSQL_ROOT_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-secret
#                   key: MYSQL_ROOT_PASSWORD
#             - name: MYSQL_DATABASE
#               value: classify
#           ports:
#             - containerPort: 3306
#           readinessProbe:
#             tcpSocket:
#               port: 3306
#             initialDelaySeconds: 20
#             periodSeconds: 5
#             timeoutSeconds: 1
#           volumeMounts:
#             - name: mysql-data
#               mountPath: /var/lib/mysql
#   volumeClaimTemplates:
#     - metadata:
#         name: mysql-data
#       spec:
#         accessModes: ["ReadWriteOnce"]
#         resources:
#           requests:
#             storage: 10Gi
#         # optional: storageClassName: "your-storageclass"
---
apiVersion: v1
kind: Service
metadata:
  name: reset-password-mysql-srv
spec:
  selector:
    app: reset-password-mysql
  type: ClusterIP
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306