apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-mysql
  template:
    metadata:
      labels:
        app: users-mysql
    spec:
      volumes:
        - name: users-mysql-storage
          persistentVolumeClaim:
            claimName: users-mysql-pvc
            
      containers:
        - name: users-mysql
          image: mysql
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: classify
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: users-mysql-storage
              mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: users-mysql-srv
spec:
  selector:
    app: users-mysql
  type: ClusterIP
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306