name: deploy-users
on:
  push:
    branches:
      -  main
    paths:
      -  'users/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      -  uses: actions/checkout@v2
      -  run: cd users && docker build -t 20011005/users .
      -  run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      -  run: docker push 20011005/users
      -  uses: digitalocean/action-doctl@v2
         with:
           token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      -  run: doctl kubernetes cluster kubeconfig save classify
      -  run: kubectl rollout restart deployment users-depl