name: deploy-materials
on:
  push:
    branches:
      -  main
    paths:
      -  'materials/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      -  uses: actions/checkout@v2
      -  run: cd materials && docker build -t 20011005/materials .
      -  run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      -  run: docker push 20011005/materials
      -  uses: digitalocean/action-doctl@v2
         with:
           token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      -  run: doctl kubernetes cluster kubeconfig save 6bb5aa54-e584-4c9b-98fe-958c2ac5fc16
      -  run: kubectl rollout restart deployment materials-depl