name: tests-subjects
on:
  pull_request:
      paths:
          - 'subjects/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  run: cd subjects && npm install && npm run test:ci
