name: tests-materials
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        FIREBASE_CONFIG: ${{secrets.FIREBASE_CONFIG}}
    steps:
      -  uses: actions/checkout@v2
      -  run: cd materials && npm install && npm run test:ci
