name: tests-shifts
on:
  pull_request:
      paths:
          - 'shifts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  run: cd shifts && npm install && npm run test:ci
